### ISSUE TITLE
[NEW_REPO]: repo_teste

### ISSUE THREAD

**Issue by VgsStudio** [Maua-Dev/devmaua_setup#23]
### project_name

repo_teste

### description

repo_teste

### privacy_type

private

### project_template

clean_mss_template (PYTHON)

**Comment by DevCommunityMaua** [comment]
Thanks for using the Issue to repo creation! :smile:\n Now you can find your repo at [github.com/Maua-Dev/repo_teste](github.com/Maua-Dev/repo_teste)
