### ISSUE TITLE
[NEW_REPO]

### ISSUE THREAD

**Issue by VgsStudio** [Maua-Dev/devmaua_setup#24]
### project_name

dev_reservation_mss

### description

É um projeto sobre reservar sala

### privacy_type

public

### project_template

clean_mss_template (PYTHON)

### CI_CD

Bump Version [FLUTTER], Create Automatic PR

**Comment by DevCommunityMaua** [comment]
Thanks for using the Issue to repo creation! :smile: Now you can find your repo at [github.com/Maua-Dev/dev_reservation_mss](github.com/Maua-Dev/dev_reservation_mss) :rocket:
