### ISSUE TITLE
[NEW_REPO]: Create a new repository in Maua-Dev

### ISSUE THREAD

**Issue by Brvilardi** [Maua-Dev/devmaua_setup#29]
### project_name

teste_soller_eh_brabo

### description

Testando se o soller realmente é brabo

### privacy_type

public

### project_template

clean_mss_template (PYTHON)

**Comment by DevCommunityMaua** [comment]
Thanks for using the Issue to repo creation! :smile: Now you can find your repo at [teste_soller_eh_brabo](https://github.com/Maua-Dev/teste_soller_eh_brabo) :rocket:
