### ISSUE TITLE
[NEW_REPO]: Create a new repository in Maua-Dev

### ISSUE THREAD

**Issue by Victor-Hugo-PZ** [Maua-Dev/devmaua_setup#64]
### project_name

teste fofo

### description

descrição linda

### privacy_type

public

### project_template

clean_front_template (REACT)

### team

Front-end

**Comment by DevCommunityMaua** [comment]
Hi @Victor-Hugo-PZ, you are not a member of the organization. Please join the organization before creating a new repo.

**Comment by DevCommunityMaua** [comment]
User is not a member of the organization :warning:
